export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    thinkingBorder: string;
    dimSeparator: string;
}

export type Theme = {
    name: string;
    colors: ThemeColors;
}

export const THEMES: Theme[] = [
    // ── Dark Themes ──────────────────────────────────────────
    {
        name: "Obsidian",
        colors: {
            primary: "#8B5CF6",
            planMode: "#A78BFA",
            selection: "#7C3AED",
            thinking: "#6D28D9",
            success: "#34D399",
            error: "#F87171",
            info: "#60A5FA",
            background: "#0F0F0F",
            surface: "#1A1A2E",
            dialogSurface: "#16213E",
            thinkingBorder: "#5B21B6",
            dimSeparator: "#2D2D44",
        },
    },
    {
        name: "Midnight",
        colors: {
            primary: "#3B82F6",
            planMode: "#60A5FA",
            selection: "#2563EB",
            thinking: "#1D4ED8",
            success: "#10B981",
            error: "#EF4444",
            info: "#38BDF8",
            background: "#0A0A0A",
            surface: "#111827",
            dialogSurface: "#1F2937",
            thinkingBorder: "#1E40AF",
            dimSeparator: "#1F2937",
        },
    },
    {
        name: "Dracula",
        colors: {
            primary: "#BD93F9",
            planMode: "#FF79C6",
            selection: "#44475A",
            thinking: "#6272A4",
            success: "#50FA7B",
            error: "#FF5555",
            info: "#8BE9FD",
            background: "#282A36",
            surface: "#21222C",
            dialogSurface: "#343746",
            thinkingBorder: "#6272A4",
            dimSeparator: "#44475A",
        },
    },
    {
        name: "One Dark",
        colors: {
            primary: "#61AFEF",
            planMode: "#C678DD",
            selection: "#3E4451",
            thinking: "#5C6370",
            success: "#98C379",
            error: "#E06C75",
            info: "#56B6C2",
            background: "#21252B",
            surface: "#282C34",
            dialogSurface: "#2C313A",
            thinkingBorder: "#4B5263",
            dimSeparator: "#3E4451",
        },
    },
    {
        name: "Gruvbox Dark",
        colors: {
            primary: "#FABD2F",
            planMode: "#D3869B",
            selection: "#504945",
            thinking: "#665C54",
            success: "#B8BB26",
            error: "#FB4934",
            info: "#83A598",
            background: "#1D2021",
            surface: "#282828",
            dialogSurface: "#3C3836",
            thinkingBorder: "#7C6F64",
            dimSeparator: "#504945",
        },
    },
    {
        name: "Nord",
        colors: {
            primary: "#88C0D0",
            planMode: "#B48EAD",
            selection: "#434C5E",
            thinking: "#4C566A",
            success: "#A3BE8C",
            error: "#BF616A",
            info: "#81A1C1",
            background: "#2E3440",
            surface: "#3B4252",
            dialogSurface: "#434C5E",
            thinkingBorder: "#4C566A",
            dimSeparator: "#434C5E",
        },
    },
    {
        name: "Tokyo Night",
        colors: {
            primary: "#7AA2F7",
            planMode: "#BB9AF7",
            selection: "#33467C",
            thinking: "#565F89",
            success: "#9ECE6A",
            error: "#F7768E",
            info: "#7DCFFF",
            background: "#1A1B26",
            surface: "#16161E",
            dialogSurface: "#24283B",
            thinkingBorder: "#414868",
            dimSeparator: "#292E42",
        },
    },
    {
        name: "Catppuccin Mocha",
        colors: {
            primary: "#CBA6F7",
            planMode: "#F5C2E7",
            selection: "#45475A",
            thinking: "#585B70",
            success: "#A6E3A1",
            error: "#F38BA8",
            info: "#89DCEB",
            background: "#1E1E2E",
            surface: "#181825",
            dialogSurface: "#313244",
            thinkingBorder: "#6C7086",
            dimSeparator: "#45475A",
        },
    },
    {
        name: "Ayu Dark",
        colors: {
            primary: "#FFCC66",
            planMode: "#D4BFFF",
            selection: "#304357",
            thinking: "#5C6773",
            success: "#BAE67E",
            error: "#FF3333",
            info: "#73D0FF",
            background: "#0A0E14",
            surface: "#0D1017",
            dialogSurface: "#1F2430",
            thinkingBorder: "#3D424D",
            dimSeparator: "#253340",
        },
    },
    {
        name: "Vesper",
        colors: {
            primary: "#FFC799",
            planMode: "#E8B4B8",
            selection: "#3B3228",
            thinking: "#6B5C4D",
            success: "#8EC07C",
            error: "#D95757",
            info: "#87CEEB",
            background: "#101010",
            surface: "#1C1C1C",
            dialogSurface: "#282828",
            thinkingBorder: "#4A3C2E",
            dimSeparator: "#333333",
        },
    },
    // ── Cyberpunk / Neon Themes ──────────────────────────────
    {
        name: "Cyberpunk",
        colors: {
            primary: "#FF00FF",
            planMode: "#00FFFF",
            selection: "#FF00FF33",
            thinking: "#8B008B",
            success: "#00FF41",
            error: "#FF073A",
            info: "#00D4FF",
            background: "#0D0221",
            surface: "#150734",
            dialogSurface: "#1A0A3E",
            thinkingBorder: "#9B30FF",
            dimSeparator: "#2A1052",
        },
    },
    {
        name: "Neon Nights",
        colors: {
            primary: "#F72585",
            planMode: "#7209B7",
            selection: "#4361EE",
            thinking: "#3A0CA3",
            success: "#06D6A0",
            error: "#FF006E",
            info: "#4CC9F0",
            background: "#10002B",
            surface: "#1B0036",
            dialogSurface: "#240046",
            thinkingBorder: "#560BAD",
            dimSeparator: "#3C096C",
        },
    },
    {
        name: "Synthwave",
        colors: {
            primary: "#FF6AC1",
            planMode: "#FED766",
            selection: "#FF6AC133",
            thinking: "#848BBD",
            success: "#72F1B8",
            error: "#FE4450",
            info: "#36F9F6",
            background: "#2B213A",
            surface: "#241B2F",
            dialogSurface: "#352A45",
            thinkingBorder: "#6943FF",
            dimSeparator: "#463465",
        },
    },
    {
        name: "Matrix",
        colors: {
            primary: "#00FF41",
            planMode: "#20C20E",
            selection: "#003B00",
            thinking: "#005500",
            success: "#00FF41",
            error: "#FF0000",
            info: "#008F11",
            background: "#000000",
            surface: "#0A0A0A",
            dialogSurface: "#0D1A0D",
            thinkingBorder: "#003300",
            dimSeparator: "#0D260D",
        },
    },
    {
        name: "Tron",
        colors: {
            primary: "#6FC3DF",
            planMode: "#DF740C",
            selection: "#18404E",
            thinking: "#1A5276",
            success: "#00E5FF",
            error: "#FF1744",
            info: "#40C4FF",
            background: "#0C141F",
            surface: "#0E1A2B",
            dialogSurface: "#132238",
            thinkingBorder: "#1A5276",
            dimSeparator: "#1C2E45",
        },
    },
    // ── Nature / Earth Themes ────────────────────────────────
    {
        name: "Forest",
        colors: {
            primary: "#2D6A4F",
            planMode: "#95D5B2",
            selection: "#1B4332",
            thinking: "#40916C",
            success: "#52B788",
            error: "#D64045",
            info: "#74C69D",
            background: "#081C15",
            surface: "#0B2418",
            dialogSurface: "#1B4332",
            thinkingBorder: "#2D6A4F",
            dimSeparator: "#1B4332",
        },
    },
    {
        name: "Autumn",
        colors: {
            primary: "#E76F51",
            planMode: "#F4A261",
            selection: "#5C3A21",
            thinking: "#8B5E3C",
            success: "#8AB17D",
            error: "#C1292E",
            info: "#E9C46A",
            background: "#1A1110",
            surface: "#261A17",
            dialogSurface: "#33221D",
            thinkingBorder: "#7F4F24",
            dimSeparator: "#3D2B22",
        },
    },
    {
        name: "Ocean",
        colors: {
            primary: "#0077B6",
            planMode: "#48CAE4",
            selection: "#023E8A",
            thinking: "#0096C7",
            success: "#06D6A0",
            error: "#E63946",
            info: "#90E0EF",
            background: "#03045E",
            surface: "#023E8A",
            dialogSurface: "#0077B6",
            thinkingBorder: "#0096C7",
            dimSeparator: "#023E8A",
        },
    },
    {
        name: "Sunset",
        colors: {
            primary: "#FF6B6B",
            planMode: "#FFA07A",
            selection: "#8B3A3A",
            thinking: "#C06C50",
            success: "#77DD77",
            error: "#FF4500",
            info: "#FFD93D",
            background: "#1A0A0A",
            surface: "#2D1515",
            dialogSurface: "#3D1F1F",
            thinkingBorder: "#8B3A3A",
            dimSeparator: "#4A2828",
        },
    },
    {
        name: "Sakura",
        colors: {
            primary: "#FFB7C5",
            planMode: "#FF69B4",
            selection: "#5E3040",
            thinking: "#8B5070",
            success: "#90EE90",
            error: "#FF6B6B",
            info: "#DDA0DD",
            background: "#1A0F14",
            surface: "#2B1A22",
            dialogSurface: "#3D2530",
            thinkingBorder: "#6B3A50",
            dimSeparator: "#4A2D3A",
        },
    },
    // ── Retro / Vintage Themes ───────────────────────────────
    {
        name: "Solarized Dark",
        colors: {
            primary: "#268BD2",
            planMode: "#6C71C4",
            selection: "#073642",
            thinking: "#586E75",
            success: "#859900",
            error: "#DC322F",
            info: "#2AA198",
            background: "#002B36",
            surface: "#073642",
            dialogSurface: "#0A4050",
            thinkingBorder: "#586E75",
            dimSeparator: "#073642",
        },
    },
    {
        name: "Monokai",
        colors: {
            primary: "#F92672",
            planMode: "#AE81FF",
            selection: "#49483E",
            thinking: "#75715E",
            success: "#A6E22E",
            error: "#F92672",
            info: "#66D9EF",
            background: "#1E1F1C",
            surface: "#272822",
            dialogSurface: "#3E3D32",
            thinkingBorder: "#75715E",
            dimSeparator: "#49483E",
        },
    },
    {
        name: "Retro Terminal",
        colors: {
            primary: "#33FF33",
            planMode: "#FFB300",
            selection: "#2A4A2A",
            thinking: "#448844",
            success: "#33FF33",
            error: "#FF3333",
            info: "#33FFFF",
            background: "#0C0C0C",
            surface: "#141414",
            dialogSurface: "#1E2E1E",
            thinkingBorder: "#336633",
            dimSeparator: "#1E3A1E",
        },
    },
    {
        name: "Commodore 64",
        colors: {
            primary: "#6C5EB5",
            planMode: "#8B8BFF",
            selection: "#3B348B",
            thinking: "#5050A0",
            success: "#68C468",
            error: "#BB4444",
            info: "#70A4B2",
            background: "#40318D",
            surface: "#4A3A9A",
            dialogSurface: "#5544AA",
            thinkingBorder: "#6C5EB5",
            dimSeparator: "#5548A8",
        },
    },
    // ── Light Themes ─────────────────────────────────────────
    {
        name: "Light",
        colors: {
            primary: "#2563EB",
            planMode: "#7C3AED",
            selection: "#DBEAFE",
            thinking: "#93C5FD",
            success: "#059669",
            error: "#DC2626",
            info: "#0284C7",
            background: "#FFFFFF",
            surface: "#F8FAFC",
            dialogSurface: "#F1F5F9",
            thinkingBorder: "#BFDBFE",
            dimSeparator: "#E2E8F0",
        },
    },
    {
        name: "Solarized Light",
        colors: {
            primary: "#268BD2",
            planMode: "#6C71C4",
            selection: "#EEE8D5",
            thinking: "#93A1A1",
            success: "#859900",
            error: "#DC322F",
            info: "#2AA198",
            background: "#FDF6E3",
            surface: "#EEE8D5",
            dialogSurface: "#E8E1CC",
            thinkingBorder: "#93A1A1",
            dimSeparator: "#D6CEB7",
        },
    },
    {
        name: "GitHub Light",
        colors: {
            primary: "#0969DA",
            planMode: "#8250DF",
            selection: "#DDF4FF",
            thinking: "#6E7781",
            success: "#1A7F37",
            error: "#CF222E",
            info: "#0550AE",
            background: "#FFFFFF",
            surface: "#F6F8FA",
            dialogSurface: "#EFF2F5",
            thinkingBorder: "#D0D7DE",
            dimSeparator: "#D8DEE4",
        },
    },
    {
        name: "Catppuccin Latte",
        colors: {
            primary: "#8839EF",
            planMode: "#EA76CB",
            selection: "#ACB0BE",
            thinking: "#9CA0B0",
            success: "#40A02B",
            error: "#D20F39",
            info: "#04A5E5",
            background: "#EFF1F5",
            surface: "#E6E9EF",
            dialogSurface: "#DCE0E8",
            thinkingBorder: "#BCC0CC",
            dimSeparator: "#CCD0DA",
        },
    },
    // ── Pastel / Aesthetic Themes ────────────────────────────
    {
        name: "Lavender Dream",
        colors: {
            primary: "#B388EB",
            planMode: "#E0AAFF",
            selection: "#3D2A58",
            thinking: "#6B4C8A",
            success: "#98D8AA",
            error: "#FF6B6B",
            info: "#A5B4FC",
            background: "#1A1028",
            surface: "#231736",
            dialogSurface: "#2E1F46",
            thinkingBorder: "#5B3D7A",
            dimSeparator: "#3A2858",
        },
    },
    {
        name: "Rose Pine",
        colors: {
            primary: "#EBBCBA",
            planMode: "#C4A7E7",
            selection: "#2A2837",
            thinking: "#6E6A86",
            success: "#9CCFD8",
            error: "#EB6F92",
            info: "#31748F",
            background: "#191724",
            surface: "#1F1D2E",
            dialogSurface: "#26233A",
            thinkingBorder: "#403D52",
            dimSeparator: "#2A283E",
        },
    },
    {
        name: "Everforest Dark",
        colors: {
            primary: "#A7C080",
            planMode: "#D699B6",
            selection: "#3D484D",
            thinking: "#7A8478",
            success: "#A7C080",
            error: "#E67E80",
            info: "#7FBBB3",
            background: "#272E33",
            surface: "#2E383C",
            dialogSurface: "#374145",
            thinkingBorder: "#4F585E",
            dimSeparator: "#414B50",
        },
    },
    {
        name: "Kanagawa",
        colors: {
            primary: "#7E9CD8",
            planMode: "#957FB8",
            selection: "#2D4F67",
            thinking: "#727169",
            success: "#76946A",
            error: "#C34043",
            info: "#7FB4CA",
            background: "#1F1F28",
            surface: "#16161D",
            dialogSurface: "#2A2A37",
            thinkingBorder: "#54546D",
            dimSeparator: "#363646",
        },
    },
]

export const DEFAULT_THEME = THEMES.find(t => t.name === "Obsidian")!